### ISSUE TITLE
Things missing, in BP, modes, Animations, Icons from the content browser

### ISSUE THREAD

**Issue by stardast132** [TheHerobrine/DarkerNodes#46] opened 2020-12-24 15:14 UTC
![image](https://user-images.githubusercontent.com/75868062/103095930-e7851880-45c7-11eb-8697-96d5286d4607.png)
![image](https://user-images.githubusercontent.com/75868062/103095944-f4a20780-45c7-11eb-85b0-afddf6e9906e.png)
![image](https://user-images.githubusercontent.com/75868062/103096037-3d59c080-45c8-11eb-933d-0fa214b70126.png)
![image](https://user-images.githubusercontent.com/75868062/103096054-48145580-45c8-11eb-8822-7912156020d0.png)
That's the one i found, you can take inspiration in this guy
https://forums.unrealengine.com/unreal-engine/feedback-for-epic/109801-unreal-engine-4-deserves-clean-ui

**Comment by TheHerobrine** [comment] 2020-12-24 15:58
Thank you very much! I'll get a lot more of icons done in January/February (for now, I'm resting for the holidays season)

I didn't know that someone actually proposed a new design like that 😮! I'll leave a comment for those who might be interested.

**Comment by TheHerobrine** [comment] 2021-01-03 00:52
I'm marking this as duplicate of https://github.com/TheHerobrine/DarkerNodes/issues/43 (I'll do all the icons in a single issue)

**Comment by TheHerobrine** [comment] 2021-01-03 22:21
Partially fixed with https://github.com/TheHerobrine/DarkerNodes/issues/43, rest is in https://github.com/TheHerobrine/DarkerNodes/issues/59

**Closed by TheHerobrine** 2021-01-03 22:21 UTC
Labels: duplicate, feature
