### ISSUE TITLE
icon align？

### ISSUE THREAD

**Issue by TheMrBigWill** [TheHerobrine/DarkerNodes#116] opened 2021-01-24 16:28 UTC
![image](https://user-images.githubusercontent.com/4563971/105636701-cbe08c80-5e69-11eb-8026-e6e4d31dcab9.png)

**Comment by TheHerobrine** [comment] 2021-01-24 16:29
This might be introduced by https://github.com/TheHerobrine/DarkerNodes/issues/112 🤔...

**Comment by TheHerobrine** [comment] 2021-01-24 16:30
@TheMrBigWill What version of the engine do you use?

**Comment by TheMrBigWill** [comment] 2021-01-24 16:32
> @TheMrBigWill What version of the engine do you use?

4.26

**Comment by TheMrBigWill** [comment] 2021-01-24 16:33
> @TheMrBigWill What version of the engine do you use?

more infomation
4k  and  200% scale dpi

**Comment by TheHerobrine** [comment] 2021-02-06 15:38
@TheMrBigWill I can't reproduce on 4.26...
![image](https://user-images.githubusercontent.com/4563971/107122715-aad06080-6899-11eb-9f8a-56fe42914dd3.png)

Could you try to go under Edit/Editor Preferences/Darker Nodes and click on "Fix Missing Elements" and tell me if that fixes anything?

**Comment by TheMrBigWill** [comment] 2021-02-07 10:20
> @TheMrBigWill I can't reproduce on 4.26...
> ![image](https://user-images.githubusercontent.com/4563971/107122715-aad06080-6899-11eb-9f8a-56fe42914dd3.png)
> 
> Could you try to go under Edit/Editor Preferences/Darker Nodes and click on "Fix Missing Elements" and tell me if that fixes anything?

I did. still got not right.
maybe the problems caused by fonts, i change font to default or other type of font. problem solved.
i used font"Titillium_Web"

**Comment by TheHerobrine** [comment] 2021-02-07 11:58
Oh! Well seems like the engine takes into account the height of the font characters and not the height of the font itself...

I'm not sure whether I can do anything about it 😕

**Comment by TheMrBigWill** [comment] 2021-02-07 14:03
> Oh! Well seems like the engine takes into account the height of the font characters and not the height of the font itself...
> 
> I'm not sure whether I can do anything about it 😕

OK. I'll ignore this.

**Comment by TheHerobrine** [comment] 2021-02-07 16:15
I can't do anything about this, it's linked to the hard-coded behavior of fonts 😞... I'll close this 😕

Another solution would be to reduce your font size a bit, but if you lose readability, it's not worth it.

**Closed by TheHerobrine** 2021-02-07 16:15 UTC
Labels: bug
