### ISSUE TITLE
Blueprint Var Node Glass Style white outline issue

### ISSUE THREAD

**Issue by CrownKing2499** [TheHerobrine/DarkerNodes#62] opened 2021-01-06 16:38 UTC
Hey,
I found one more problem, when setting the "Blueprint Var Node Style" to Glass, once you zoom out a little inside the blueprint, all nodes using the Glass style are getting a weird white outline and some of them look highlighted, if the zoom is 1:1 everything looks fine tho!

Zoom 1:1 ![Zoom 1to1](https://user-images.githubusercontent.com/52871543/103795152-ed5a0f80-5045-11eb-9ea9-787b53de5123.png)

Zoom -1 and above: 
![Zoom -1](https://user-images.githubusercontent.com/52871543/103795187-f77c0e00-5045-11eb-8cd8-b873f687152e.png)

**Comment by TheHerobrine** [comment] 2021-01-06 16:57
This is a duplicate of https://github.com/TheHerobrine/DarkerNodes/issues/63, I'm closing this 😉

**Closed by TheHerobrine** 2021-01-06 16:57 UTC

**Comment by CrownKing2499** [comment] 2021-01-06 17:08
> This is a duplicate of #63, I'm closing this 😉

Oh wow, it showed me an error when posting it the first time so I posted it again and now it shows both lmao, sorry for that!

**Comment by TheHerobrine** [comment] 2021-01-06 17:09
Ahah, no worry!
